version: "3.8"

services:
  app:
    build: .
    ports:
      - "6060:9090"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://cocktails-backend:password@db/cocktails
    volumes:
      - .:/app
    command: pnpm start

  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: cocktails-backend
      POSTGRES_DB: cocktails
