name: Cocktail Backend Postgres workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up space on GitHub Actions runner
        run: |
          echo "🧹 Cleaning up GitHub Actions runner to free space"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/lib/jvm
          df -h

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/olga-urentseva/cocktails-backend-postgres:${{ github.sha }} .
          docker push ghcr.io/olga-urentseva/cocktails-backend-postgres:${{ github.sha }}

      - name: Build and push migration image
        run: |
          docker build --target build -t ghcr.io/olga-urentseva/cocktails-migrations:${{ github.sha }} --no-cache --progress=plain .
          docker push ghcr.io/olga-urentseva/cocktails-migrations:${{ github.sha }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_RSA_KEY }}

      - name: Add remote host to known_hosts
        run: echo "159.223.195.255 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFy62mbbtRdNw9jMhkSihYMsDAxDGY8ggWdsEMWY+x/8NJhI/LUhK/92pynfUXu4svVpTAcxbfI92PimBIQdJ5c6kyqDsh+ZYDxo6NhfYZrv/ZH3nrjHohdDHls4izsI95WmC3RLgQS0VJp8/Nv2+xCXfh7EoWtg7NulP/1HZVshGs6kllq7Z5Gxou8zC+2L7U1KGz8MzvZIUNmgdZEeH5O256Lg15y7v455o3i8f4Byzx7nC7MCUEwAmwkQPLTcHskIh1qkCvWV7gKOSMwsYkk+Kp3szP80EjVcyQCjC40vmsNFTlnowor5lKhtUjQ17BtLySbDVuJw/3k5H85tM8AWZGsYQfJET6DLska+dIXVs+HCaFXrJDgljJ0lIexL78nkGbYG5KbaMSzs2ZCe1xF+7evqzsvG+68x5A7BqrfJC3wzobDQaFJpU8Sibuva4J+eynb1HhbfKD50dbjhYuk3VE4eTDTHvdgpFSn5pkjDzp/SrVTsyHDlA6MUaiFFs=" >> ~/.ssh/known_hosts

      - name: Connect to remote server and deploy stack
        run: |
          docker context create --docker host=ssh://deployer@159.223.195.255 my-server
          docker context use my-server

      - name: Re-login on remote context
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy stack
        run: GIT_COMMIT_SHA=${{ github.sha }} docker stack deploy -c ./docker-compose-production.yaml --with-registry-auth cocktails-backend-postgres

      - name: Pre-pull migrations image on server
        run: docker pull ghcr.io/olga-urentseva/cocktails-migrations:${{ github.sha }}

      - name: remove migration service if exists
        run: |
          docker service rm cocktail-migrations || echo "Service cocktail-migrations not found, skipping removal"

      - name: Run migrations via migration service
        run: |
          docker service create \
            --name cocktail-migrations \
            --detach=false \
            --env DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --env GIT_COMMIT_SHA=${{ github.sha }} \
            --network db \
            ghcr.io/olga-urentseva/cocktails-migrations:${{ github.sha }} \
            pnpm drizzle-kit migrate

          # docker service rm cocktail-migrations

      - name: Clean up images
        run: docker image prune -f
